[package]
name = "db-client"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { version = "0.2.2" }
gpui-component = "0.5.0"
core-text = "=21.0.0"
rusqlite = { version = "0.32", features = ["bundled"] }
futures = "0.3"

[package.metadata.bundle]
name = "DB Client"
identifier = "com.jhorman.dbclient"
version = "1.0.0"
copyright = "Copyright Jhorman 2026"
category = "Productivity"
